Challenge 2 intro to testing
ArielMD/react-certification-2021 pull request #1
Opened 2021-07-26 22:05 UTC by ArielMD

# Description
I have added main componentes to implement Home screen.
These change permit to visualize the video list, navbar and sidebar.
 
 # Testing
 I have added coverage for testing all new componets.
![image](https://user-images.githubusercontent.com/32398171/127064643-68d4f0b6-aaf1-490d-b560-75b761d74867.png)
 
  ## Screenshots 
Design
![image](https://user-images.githubusercontent.com/32398171/127065012-965c75d9-1455-453c-9e37-23e6faa4ded4.png)

Code
![image](https://user-images.githubusercontent.com/32398171/127065071-286efec5-f5d2-4fec-85b9-0249db77e141.png)

2021-07-28 03:01 UTC, omarscd requested changes
Bastante completo, felicidades!

Te dejo algunos comentarios de cositas que creo que se pueden mejorar.

2021-07-28 03:01 UTC, omarscd commented on src/components/Layout/Layout.styles.js
> +export default Container;
Para mantenerlo consistente con los otros `*.styles.js` que exportan cada componente de manera individual, creo que no debería tener el `export default`

2021-07-28 03:01 UTC, omarscd commented on src/index.jsx
> +import '@fortawesome/fontawesome-free/css/all.css';
Esto es para definir estilos generales?
En caso de que así sea, sería posible eliminar la línea de `import './global.css';` para evitar conflictos?

2021-07-28 03:01 UTC, omarscd commented on src/components/UserProfile/UserProfile.styles.js
> +export const ToggleButton = styled.div``;
Si no se le van a agregar estilos, creo que sería más conveniente simplemente utilizar la etiqueta `div`

2021-07-28 03:01 UTC, omarscd commented on src/components/Navigation/Navigation.component.jsx
>    };
Creo que sería buena idea que al momento de mostrar la barra de búsqueda, le hagas focus al campo de texto, de lo contrario, el usuario tiene que dar dos clics para empezar a escribir

2021-07-28 03:01 UTC, omarscd commented on src/components/UserProfile/UserProfile.component.jsx
> +    >
💅🏼

2021-07-28 03:01 UTC, omarscd commented on src/components/Navigation/Navigation.component.jsx
> +  const [hiddeSidebar, setHiddeSidebar] = useState(true);
pequeño typo aquí, creo que quisiste decir `Hidden`

Como nota aparte, generalmente las variables de tipo booleano se nombran comenzando con la palabra `is` o `has` y se trata de utilizar nombres afirmativos, por ejemplo: `isSidebarVisible`. Aquí te dejo un pequeño artículo con tips https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig

2021-07-28 03:01 UTC, omarscd commented on src/components/Explore/Explore.component.jsx
> +};
Me agrada esta propuesta!

2021-07-28 03:01 UTC, omarscd commented on src/pages/Home/Home.styles.js
> +export const MainSection = styled.section`
considera utilizar la etiqueta `<main>` si lo vas a usar para el contenido principal de la página

2021-07-28 03:01 UTC, omarscd commented on src/pages/Home/Home.page.jsx
> +        )}
Buen trabajo agregando la distinción

Si es un canal, no crees que sería más apropiado que el nombre del prop fuera `channel` en lugar de `video`?

2021-07-28 18:14 UTC, ArielMD commented on src/index.jsx
> +import '@fortawesome/fontawesome-free/css/all.css';
Es importación para usar los iconos de fontawesome, aunque el global.css ya no lo uso, lo eliminare

2021-07-28 18:15 UTC, ArielMD commented on src/components/UserProfile/UserProfile.styles.js
> +export const ToggleButton = styled.div``;
Correcto, lo cambiaré en todos los casos

2021-07-28 18:16 UTC, ArielMD commented on src/components/Navigation/Navigation.component.jsx
>    };
No había pensado es ese caso, lo implementaré

2021-07-28 18:27 UTC, ArielMD commented on src/components/Navigation/Navigation.component.jsx
> +  const [hiddeSidebar, setHiddeSidebar] = useState(true);
Ya leí el articulo, cambiaré el nombre de las variables, gracias por el dato

2021-07-28 18:28 UTC, ArielMD commented on src/pages/Home/Home.page.jsx
> +        )}
Cierto

2021-07-29 23:30 UTC, omarscd approved these changes
LGTM

Solo toma en cuenta el último comentario que te dejé, por lo pronto, puedes hacer merge de esta rama

2021-07-29 23:30 UTC, omarscd commented on src/pages/Home/Home.page.jsx
> +            <ChannelCard key={item.id.channelId} channel={item} />
sería bueno también que los componentes `VideoCard` y `ChannelCard` recibieran la información desglosada en los props, por ejemplo `title`, `thumbnail`, `description`, etc, en lugar de un objeto.
Pero si quieres eso déjalo para el siguiete PR

2021-07-31 01:38 UTC, ArielMD commented on src/pages/Home/Home.page.jsx
> +            <ChannelCard key={item.id.channelId} channel={item} />
Esta bien, gracias tomaré este comentario para la siguiente entrega.

2021-08-02 03:43 UTC, merged